### PR TITLE
Add `isEditable` and `isReadOnly`

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Comment by amitaibu** [comment]
Ready for review.

**Comment by amitaibu** [comment]
I just hit a use case where I need those, is there a chance to get it in -- or you prefer not to?

**Comment by stoeffel** [comment]
awesome thanks! Making you a contributor to this repo...

**Comment by stoeffel** [comment]
Just found https://github.com/Gizra/elm-editable-webdata . This is awesome! was thinking about building something like this as well.

**Comment by amitaibu** [comment]
Thanks :)

Yeah, just pushed it few hours ago. I was about to ping you to get a review or thoughts, before I publish

**Pull request merged**
