### PR TITLE
Upgrade to 0.19.0

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Review by stoeffel — APPROVED** [review]
lgtm. thanks!

**Comment by amitaibu** [comment]
Thanks :) Can you please publish this as-well (not sure if I have access to do so)

**Comment by amitaibu** [comment]
👍 Sure, I'll try

Just confirming, to make sure I'm not doing a mistake - I see that we already have a `2.0.0` tag, but in `elm.json` (and previously in elm-`package.json`) we have it as https://github.com/stoeffel/editable/blob/c09ae7fd2b0b62d793466e9f33fbc1ef3b3a3d21/elm.json#L6

I assumer I should change it to 2.0.0, commit, and from there `elm bump`, right?

**Comment by amitaibu** [comment]
Great, published :)

**Comment by stoeffel** [comment]
Thanks ❤️

**Pull request merged**
